### ISSUE TITLE
iOS support? - DXT5Crunched 

### ISSUE THREAD

**Issue by yosun** [gpvigano/AsImpL#31]
### New features and suggestions

This is both a bug and feature request.  Unity iOS build doesn't work with this importer? 

### Problems & bugs

73: [Unity] -----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
74: [Unity] Compilation failed: 1 error(s), 0 warnings
75: [Unity] Assets/AsImpL/Scripts/Dataset/ModelUtil.cs(89,52): error CS0117: `UnityEngine.TextureFormat' does not contain a definition for `DXT5Crunched'
76: [Unity] /UNITY_PATH/Unity/Unity-2018_1_6f1/PlaybackEngines/iOSSupport/Variations/il2cpp/Managed/UnityEngine.CoreModule.dll (Location of the symbol related to previous error)
77: [Unity] ERROR: Assets/AsImpL/Scripts/Dataset/ModelUtil.cs(89,52): error CS0117: `UnityEngine.TextureFormat' does not contain a definition for `DXT5Crunched'
78: [Unity] UnityEditor.CloudBuild.BuildLogger:HighlightUnityErrors(String, String, LogType)
79: [Unity] Assets/AsImpL/Scripts/Dataset/ModelUtil.cs(89,52): error CS0117: `UnityEngine.TextureFormat' does not contain a definition for `DXT5Crunched'
80: [Unity] ERROR: Error building Player because scripts had compiler errors
81: [Unity] UnityEditor.CloudBuild.BuildLogger:HighlightUnityErrors(String, String, LogType)
82: [Unity] Error building Player because scripts had compiler errors
83: [Unity] Player export failed. Reason: Error building Player because scripts had compiler errors
84: ! build of 'default-ios' failed. compile failed

#### Environment
Unity Cloud Build latest 2018.1 stable
iOS deployment

**Comment by gpvigano** [comment]
I tried to fix this issue with my commit c072f7733f15dac70e3178f8c1182bfd36f2fc5f, but I don't have iOS and I can't test it. Could you test it and give me a feedback, please? Thank you very much for your contribution.

**Comment by zephyo** [comment]
Hi! I've also encountered this issue when building for iOS.
<img width="771" alt="screen shot 2018-07-12 at 8 08 24 pm" src="https://user-images.githubusercontent.com/22963510/42670387-63859a98-860f-11e8-8a63-d5126c0112b0.png">

**Comment by gpvigano** [comment]
That error appears in a script (LPMAssets.cs) that does not belong to AsImpL.
Find the code in your script where `DXT5Crunched` appears and think about changing that code, maybe you can wrap it with `#if UNITY_STANDALONE_WIN` and `#endif` like I did [here](https://github.com/gpvigano/AsImpL/commit/4b398e13bff1989271db3c4c7799e57d719146cc#diff-539e667ceb3cbb64caeda42d346383ddR90), but it depends on how the code works.
I can't help you without knowing the script, anyway the problem is the use of `DXT5Crunched` that is available only on DirecX-based platforms.
