### ISSUE TITLE
Inverting Face issue

### ISSUE THREAD

**Issue by kishanhebbar** [gpvigano/AsImpL#33]
I am facing very strange import issue.
AsImpL seems to have some minor issue of inverting faces. 

Same model is tested by importing with AssImpL and Unity importer.
![compareimage](https://user-images.githubusercontent.com/40821135/43587797-aac643ce-9688-11e8-8090-848302268863.png)
![invetedface1](https://user-images.githubusercontent.com/40821135/43587804-ae221804-9688-11e8-9950-9b3b71e72751.png)
![comparision 2](https://user-images.githubusercontent.com/40821135/43588240-af43b66a-9689-11e8-844d-299612c761a1.png)

**Link to the 3D models themselves**
[Basin Model](https://drive.google.com/open?id=13sq3OQZ4ttpDRzG4TwCwajS8wrPOJ1zA)
[Wall Model](https://drive.google.com/open?id=1JDNgCb4jdfU1Oxju6TrznQt5U3cgS7wJ)

In the import settings I have tried with both "Convert to Double sided" On & off

Can you kindly look into it

Thanks 

cheers ;)

**Comment by gpvigano** [comment]
Using the last version I got a different result (you provided only the OBJ files, so the materials are replaced with a default material here):
![issue33-test](https://user-images.githubusercontent.com/20297129/43591386-88982552-9673-11e8-9aa8-127e6d930eb1.png)
Some of the faces here are incorrect, due to the known issue #19 (wrong triangulation), I guess you are using a previous version of AsImpL, with no support for faces with more than 4 vertices, if so you don't have flipped faced, simply you don't have them, they are skipped.
Which version of AsImpL are you using? Which version of Unity? (following the issue template would be a good idea here...)

**Comment by kishanhebbar** [comment]
Hey, It worked perfectly fine after the update.  
Except for the small wrong triangulation) issue. 

Thanks ,
