### ISSUE TITLE
Memory leak after deleting Models

### ISSUE THREAD

**Issue by GTO2013** [gpvigano/AsImpL#43]
Hi,
thanks for sharing your code! I use it to generate a dataset of images out of 3d models (around 3500 models of cars). I load one model, render a couple of images, delete it and load the next one. But the memory consumption just grows and grows. This is after around 300 models:

![image](https://user-images.githubusercontent.com/9764527/89568851-318d7d80-d824-11ea-98d9-5a93fb0312f7.png)

This is how I load the model:

              
```
loadedObject = new GameObject();
ObjectImporter objImporter = loadedObject.AddComponent<ObjectImporter>();
objImporter.ImportFile(objPath, loadedObject.transform, importOptions);
                
 action = delegate () {
          objLoaded = true;
 };

objImporter.ImportingComplete += action;
```

And this is how I destroy it:
```
obj.GetComponent<ObjectImporter>().ImportingComplete -= action;
Destroy(obj);
```

Am I just missing something or is this a bug? I noticed that you keep the loadedModels in a dictionary. I deleted the entry after the model was created, but this didnt solve it.

Environment:
Version AsImpL: 698f024
Unity 2019.4.4f1

Thanks for your help!

**Comment by gpvigano** [comment]
Sorry for the late response, I hope I can still help you.
I guess the problem is that in Unity materials and textures are not destroyed when destroying a game object.
What about adding a static method to `ModelUtil` that can be called to destroy a game object and, recursively on its children, all the used materials and textures?
Maybe it could be quite a dangerous method, because in general materials and textures can be shared with other game objects.
Another problem arises if you set `importOptions.reuseLoaded=true` before calling `objImporter.ImportFile(...)`, then you destroy the loaded object: references to loaded game objects are kept in memory anyway, with references to destroyed textures, not a good idea.
We could add this "exterminator" method with a clear documentation about its collateral effects.
We also need a mechanism to prevent dangling references to game objects in case the `reuseLoaded` optino is on, but this could be a new issue.
What's your opinion?

**Comment by GTO2013** [comment]
Hi, thanks for your reply! I havent set the reuseLoaded option, so it cant be that. I "fixed" the problem by using this

```
            foreach (MeshFilter f in currentCar.GetComponentsInChildren<MeshFilter>())
            {
                Destroy(f.sharedMesh);
            }

            Destroy(currentCar);
            UnityEditor.EditorUtility.UnloadUnusedAssetsImmediate();
            Resources.UnloadUnusedAssets();
```

This fixes the problem for me, but a proper method to unload the model afterwards would definitely be nice! 👍

**Comment by gpvigano** [comment]
Thank you for your reply. Nice to see that you fixed your problem, anyway your fix works only in Unity Editor, so an alternative would be anyway useful for a build, at run-time. Anyway such a method, checking for unused assets, would be better than the previously mentioned "exterminator" method, but I have not a clear idea about its implementation right now.

Just a question about your code: I noticed you destroy the meshes, what about simply calling `DestroyImmediate(currentCar)`?

**Comment by GTO2013** [comment]
DestroyImmediate does not solve the problem, since the only difference to Destroy is that it sets references to null immediately instead of at the end of the frame :)

**Comment by gpvigano** [comment]
In [this commit](https://github.com/gpvigano/AsImpL/commit/f597eaa07ed3bdb87fc9646c7c365d0d897420e6) I implemented a new component `ModelReferences` that is automatically added to the loaded object by the `Loader`. This component keeps track of the resources used by the loaded object and takes care of their destruction when the loaded object is destroyed. Some changes were needed in `Loader` and `ObjectImporter` to integrate this component in the loading process.

I also added a new example scene (`004_Import_DestroyTest`) to test memory deallocation by loading and destroying models multiple times: the same model is periodically destroyed and reloaded after a while (default = 1 second, but it can be modified in the Editor Inspector).

In Unity 2018.1 and newer it is possible to inspect the referenced resources in the `ModelReferences`  component of a loaded object in the Editor inspector.
