### ISSUE TITLE
No face and No material

### ISSUE THREAD

**Issue by keremkrz** [gpvigano/AsImpL#53]
![resim_2023-01-31_031331019](https://user-images.githubusercontent.com/104232003/215625672-e1df8a6d-9c75-442b-aff7-b0e3e2f7495e.png)

Object: default has no face defined.
No material library defined. Using a default material.

I could not provide a healthy use, I would appreciate if you help

**Comment by gpvigano** [comment]
I have not enough information to help you. I suspect your problem could be caused by an unsupported OBJ feature, so I just committed a fix in order to detect unsupported features while parsing the OBJ file. Please try with the new version and keep note of possible further warnings. I hope this can be helpful.
