### ISSUE TITLE
Uri not being escaped

### ISSUE THREAD

**Issue by maessof91** [gpvigano/AsImpL#54]
> **WARNING:** Any issue that does not follow the below template could be closed and not re-opened until the template structure is adhered to.

#### Precheck

> * For proposing a new feature, please check existing open and closed issues before creating a duplicate
> * Add comment to an issue only if related to it (otherwise choose a different issue or create a new one)
> * Please do not write long text in issue title, choose a short title for the topic, then add your text to the issue body
> * For bugs, do a quick search and make sure the bug has not yet been reported
> * Finally, follow the code of conduct (at <https://github.com/gpvigano/AsImpL/blob/master/CODE_OF_CONDUCT.md>)
> 
> **Choose one of the categories below and follow the related template (fill the coosen section, delete everything else, including this text).**

### New features and suggestions

Follow the rules above and try to be as clear as possible.

#### Environment
>Please specify:
> * version of AsImpL (Github master commit hash or at least date/hour when you downloaded it)
> * version of Unity3D (e.g. Unity 5.4.4f1)

#### Steps to reproduce

> For issues related to a specific 3D model try to identify which are the features of the model that cause the issue, or at least attach as a ZIP archive a very simple (lightweight) 3D model that has the same problem. If this is not possible you can send that model via e-mail to <gpv.code@gmail.com> with a subject starting with "*[AsImpL] 3D model-*", then you can create a related issue.

> For general bugs, attempt to recreate the issue with a simple example code and provide steps to reproduce if possible. Include code samples, errors and stacktraces if appropriate.

#### Expected behavior

> For general bugs, briefly describe what you expect should happen.

#### Current behavior

> For general bugs, briefly describe what is actually happening.

**Comment by maessof91** [comment]
See updated function fixed here,updated first line, giving errors on android for spaced files.
   
   public IEnumerator DownloadUri(string uri, bool notifyErrors)
        {
            uri = Uri.EscapeUriString(uri);

**Comment by maessof91** [comment]
File is AsImpL\Scripts\IO\FileFilesystem.cs

**Comment by maessof91** [comment]
but that gave me issues on pc so added a line to also normalise the mtl and png etc

uri = uri.Replace('\\', '/');
uri = Uri.EscapeUriString(uri);

**Comment by maessof91** [comment]
uri = uri.Replace('\\\\', '/');
            uri = Uri.EscapeUriString(uri);

**Comment by gpvigano** [comment]
`uri = uri.Replace('\\', '/')` sounds good, but I suspect that `Uri.EscapeUriString` can have undesired side-effects in some cases (I suggest to read [this link on stackoverflow](https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring), see also [the warning on .NET documentation](https://learn.microsoft.com/en-us/dotnet/api/system.uri.escapeuristring?view=net-6.0)).
In [this answer on Stack Overflow](https://stackoverflow.com/questions/1546419/convert-file-path-to-a-file-uri) other issues are discussed.
Maybe the best choice is to let the user prepare the URL instead of trying to guess what kind of address is passed and choosing a proper conversion.

Please try to be more concise and clear in your comments: there is a menu on the top-right side of each comment to edit/hide/delete the comment. Please also fix the first comment of this issue, replacing the default text with the issue description, thanks.
