### ISSUE TITLE
Option to generate mesh colliders for loaded models

### ISSUE THREAD

**Issue by rezadarooei** [gpvigano/AsImpL#8]
Hi
Loaded models do not contain any mesh collider or Rigid body.If it is possible please add this option to your importer to add RIgid body and mesh collider.which means add some post-processing options for your awesome importer
Thanks a lot

**Comment by gpvigano** [comment]
I addressed this issue in my commit 6c0e72aea7ba9fd5188fcac6b389a132e7190fe6, adding options to generate mesh colliders.
Mesh colliders now can be automatically built along with meshes.

Known issues:
* if an object is split into sub-objects because its mesh
has more than 65K vertices, multiple mesh colliders are generated.
* if a mesh has too many smooth surface regions, convex meshes may not
work (you get an error and no collider is available for that mesh)

**About rigidbodies:** a rigidbody can be configured in several ways, maybe you can just add a Rigidbody to the imported object (e.g. `loadedObject.AddComponent<Rigidbody>()`) and configure it as you need. To create a "default" rigidbody we must answer to some questions:
* gravity should be enabled?
* kinematic or not?
* what about constraints?
* a single rigidbody for the whole object or a set of rigidbodies attached to sub-objects?
* ...
As you can see it is not so easy, unless we focus only on a simple common case (which one?).
